### ISSUE TITLE
Cluster CIS datapackages

### ISSUE THREAD

**Issue by NikGrimm** [spedas/pyspedas#303]
I started to use the load routines for the Cluster Spacecraft data. For my study, I need the omni directional ion energy flux density, which should be included in the CIS data packages, but I was not able to load such data with PySpedas (cluster.cis()). Is it possible to load the energy flux from the CIS instrument?

**Comment by supervised** [comment]
It should be possible to load it from CSA using the load_csa function here:

https://github.com/spedas/pyspedas/blob/master/pyspedas/cluster/load_csa.py

But it wasn't working when I tried just now.

**Comment by NikGrimm** [comment]
The load_csa function isn't working for me, either.  The file can be downloaded by the routine, but then I always get this error
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\Spedas_Data\\clusterCSA_Download_20230120_0802\\C1_CP_CIS-CODIF_HS_H1_MOMENTS\\C1_CP_CIS-CODIF_HS_H1_MOMENTS__20010201_000000_20010203_000000_V220805.37.istp.cdf'

**Comment by supervised** [comment]
I found and fixed the issue - the CDF routine was crashing while trying to load an extra CDF that's sent along with the data. Update to pyspedas v1.4.21 or later to get the fix. 

I also released a notebook that shows how to load and plot the differential particle flux from CIS:

https://github.com/spedas/pyspedas_examples/blob/master/pyspedas_examples/notebooks/Cluster_CIS_data_from_CSA.ipynb


I'm not an expert with these data, so I suggest taking a look at the CIS User Guide if you haven't yet: 

https://caa.esac.esa.int/documents/UG/CAA_EST_UG_CIS_v37.pdf

Hope this helps!

**Comment by NikGrimm** [comment]
I update my pyspedas to v1.4.21, but still get the same error I reported above:
![Screenshot 2023-01-24 115315](https://user-images.githubusercontent.com/123059856/214273612-2b6f565d-b6a1-4608-b4e3-702c5169c548.png)
Do I have to update something else, or is where another problem?

**Comment by supervised** [comment]
ah, sorry - there was another bug in how the paths were concatenated. It should be fixed in 1.4.22 now

**Comment by supervised** [comment]
Happy to help! Thanks again for the bug report!
